# Generated by Django 3.2.4 on 2021-06-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_cameras_port'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
    ]
